import dotenv from 'dotenv'
dotenv.config()

const {
	AUTH0_SECRET,
	AUTH0_BASE_URL,
	AUTH0_ISSUER_BASE_URL,
	AUTH0_CLIENT_ID,
	AUTH0_CLIENT_SECRET,
	AUTH0_AUDIENCE,
	AUTH0_COOKIE_NAME,
	DEPLOY_URL,
} = process.env

export const variables = {
	AUTH0_SECRET,
	AUTH0_BASE_URL: DEPLOY_URL || AUTH0_BASE_URL,
	AUTH0_ISSUER_BASE_URL,
	AUTH0_CLIENT_ID,
	AUTH0_CLIENT_SECRET,
	AUTH0_AUDIENCE,
	AUTH0_COOKIE_NAME,
}
